# Generated by Django 4.2.3 on 2023-07-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('SP', 'Спорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('WE', 'Погода')], default='SP', max_length=25, unique=True),
        ),
    ]
