# Generated by Django 4.2.3 on 2023-08-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_subscribers_categorysubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySubscriber',
        ),
    ]
